/**
 * 《回门》场景模块：exp_ancestral_spirits
 */


import { createScene, createChoice } from '../../../js/engine/sceneFactory.js';

export const scenes = {
    huimen_exp_ancestral_painting: createScene('huimen_exp_ancestral_painting', {title:"祖像",text:"你在祖祠的角落里发现一幅画像。\n\n画像已经发黄，画上是一个穿长袍的老者，面目威严。画像下方写着\"周氏开基祖\"。\n\n你盯着画像看，发现老者的眼睛似乎在动。你再仔细看，他的嘴角也微微上扬。\n\n\"你来了。\" 画像说，\"周家等你很久了。\"\n\n你后退一步，画像却从墙上飘下来，悬在你面前。\n\n\"秀兰的事，是我定的。\" 老者说，\"一个女人，坏了周家的名声，就必须除掉。你认同吗？\"",effects:{"sanity":-10,"yin":3},choices:[createChoice({"text":"说不认同","next":"huimen_exp_ancestral_painting_defy","effects":{"sanity":5,"yin":-3}}),createChoice({"text":"沉默","next":"huimen_exp_ancestral_painting_silent","effects":{"yin":2}})]}),
    huimen_exp_ancestral_painting_defy: createScene('huimen_exp_ancestral_painting_defy', {title:"驳祖",text:"你说：\"我不认同。人命不是名声能换的。\"\n\n画像老者的脸扭曲了，像被火烧的纸一样卷曲起来。\n\n\"逆子！\" 他尖叫，\"你敢反驳祖先！\"\n\n\"如果祖先错了，就该被反驳。\" 你说。\n\n画像\"砰\"地一声烧起来，化作灰烬落在地上。灰烬里有一张黄符，符上写着\"周氏开基祖之灵位\"。\n\n你把黄符踩碎。祖祠里的阴影发出一阵骚动，然后渐渐退散。",effects:{"sanity":10,"yin":-10,"setFlag":"huimen_exp_defied_ancestor"},choices:[createChoice({"text":"回村街","next":"huimen_exp_village_street","effects":{"yin":1}})]}),
    huimen_exp_ancestral_painting_silent: createScene('huimen_exp_ancestral_painting_silent', {title:"沉默",text:"你沉默了。\n\n画像老者满意地点点头：\"好孩子。周家需要你这样的人。\"\n\n他伸出手，想拍你的肩膀。你侧身躲开。\n\n\"你不认同？\" 老者问。\n\n\"我不说话，不代表我认同。\" 你说，\"我只是不想和一张纸争辩。\"\n\n画像老者的脸僵住了，然后缓缓飘回墙上，恢复了原来的模样。\n\n你知道，他还会再找机会。",effects:{"sanity":-3,"yin":2},choices:[createChoice({"text":"回村街","next":"huimen_exp_village_street","effects":{"yin":1}})]}),
    huimen_exp_ancestral_women_wall: createScene('huimen_exp_ancestral_women_wall', {title:"女墙",text:"你在祖祠的后墙发现一面\"女墙\"。\n\n墙上密密麻麻刻着很多名字，都是女子的名字。周氏秀兰、周氏柳红、周氏云袖……每一个名字后面都刻着\"不祥\"、\"沉塘\"、\"活埋\"。\n\n你数了数，一共有三十七个名字。\n\n[red]三十七个女子，三十七条命，撑起周家所谓的\"清白\"。[/red]\n\n你用手指描摹那些名字，感到一阵刺痛。墙在吸你的血，每描一个字，你的指尖就渗出一滴血。\n\n\"把我们的名字记下来。\" 一个声音说，\"别让世人忘了。\"",effects:{"sanity":-10,"yin":3,"setFlag":"huimen_exp_saw_women_wall"},choices:[createChoice({"text":"用血在墙上写正名","next":"huimen_exp_ancestral_women_wall_rename","effects":{"sanity":-5,"yin":5}}),createChoice({"text":"把名字抄下来","next":"huimen_exp_village_street","effects":{"yin":1,"addItem":"女子名单"}}),createChoice({"text":"把这些名字抄下来，贴在村口","next":"huimen_exp_zhou_women_alt"}),createChoice({"text":"你已见过女墙，带红漆回来重新描红每一个名字","next":"huimen_exp2_ancestral_women_wall_2","condition":{"flag":"huimen_exp_saw_women_wall"},"hidden":true,"effects":{"sanity":-3,"yin":2}})]}),
    huimen_exp_ancestral_women_wall_rename: createScene('huimen_exp_ancestral_women_wall_rename', {title:"重写",text:"你咬破手指，在每个名字后面写下\"正名\"二字。\n\n血字渗入墙面，那些原本黯淡的名字一个个亮起来。墙里传来女子的哭声，这次不是悲伤，而是解脱。\n\n\"谢谢……\" 她们说，\"终于有人看见我们了。\"\n\n墙面开始剥落，露出底下的红砖。红砖上刻着新字：\n\n[faded]\"周氏女子，各有名姓，各有来生。\"[/faded]\n\n你感到胸口的压抑轻了很多，像是卸下了三十七年的重担。",effects:{"sanity":10,"yin":-15,"setFlag":"huimen_exp_renamed_women_wall"},choices:[createChoice({"text":"回村街","next":"huimen_exp_village_street","effects":{"yin":1}}),createChoice({"text":"把名单带出村子，让世人知道","ending":"huimen_exp_ending_name_list","condition":{"hasItem":"女子名单"},"effects":{"yin":-5}}),createChoice({"text":"在村口立一块名碑","ending":"huimen_exp_ending_name_stone","condition":{"flag":"huimen_exp_renamed_women_wall"},"effects":{"yin":-5}}),createChoice({"text":"一切已明，打开阴阳簿","next":"true_ending_gate","condition":{"flag":"clues_assembled"},"hidden":true})]})
};
