/**
 * 《回门》场景模块：exp_moon_journey
 */


import { createScene, createChoice } from '../../../js/engine/sceneFactory.js';

export const scenes = {
    huimen_exp_moonlit_path_end: createScene('huimen_exp_moonlit_path_end', {title:"路尽",text:"你走到小路尽头。\n\n那里有一扇纸门，门上画着秀兰的像。她盖着红盖头，盖头下露出一双眼睛，正看着你。\n\n\"你走到这里了。\" 她说，\"再往前，就是出村的路。\"\n\n你伸手去推门，纸门却像有生命一样贴在你手上。门上的秀兰开口说话：\n\n\"出去可以。但你要答应我一件事。\"\n\n[whisper]\"每年七月半，回来看我一眼。\"[/whisper]\n\n[red]你意识到，这不是出口，是一个约定。[/red]",effects:{"sanity":-5,"yin":2},choices:[createChoice({"text":"答应她","next":"huimen_exp_moonlit_escape","effects":{"sanity":3,"yin":-5}}),createChoice({"text":"拒绝，转身回村街","next":"huimen_exp_village_street","effects":{"yin":2}}),createChoice({"text":"答应她每年七月半来陪她看月亮","next":"huimen_exp_moon_pact_alt"})]}),
    huimen_exp_moonlit_escape: createScene('huimen_exp_moonlit_escape', {title:"月下离村",text:"你答应了秀兰。\n\n纸门轻轻打开，月光像水一样涌进来。你踏出门，发现自己站在村口的石板路上，身后是沉睡的山村。\n\n天边泛起鱼肚白。纸人们倒在路边，像被风吹倒的稻草人。\n\n你没有回头，一直往前走。你知道秀兰在看着你，但她的目光不再是冷的。\n\n[whisper]\"记得回来。\"[/whisper]",effects:{"sanity":10,"yin":-10},choices:[createChoice({"text":"独自离开","ending":"huimen_exp_moonlit_escape","effects":{"yin":-1}}),createChoice({"text":"带秀兰一起走","ending":"huimen_exp_ending_flower_rain","condition":{"flag":"xiulanMercy"},"effects":{"yin":-5}}),createChoice({"text":"逃回城市，假装一切没发生过","next":"huimen_exp_escape_aftermath"})]}),
    huimen_exp_moonlit_grave: createScene('huimen_exp_moonlit_grave', {title:"月下孤坟",text:"你沿着月光小路走，来到一座孤坟前。\n\n坟没有碑，只有一块扁平的石头。石头上放着一束枯萎的桂花。\n\n你蹲下身，发现石头下面压着一张纸：\n\n[faded]\"无名女子之墓。周家所害，无人祭奠。过路者若有余心，请献一花。\"[/faded]\n\n[red]这不是秀兰的坟。这是另一个被遗忘的女子。[/red]\n\n你把那束枯桂花扶正，又从路边摘了一朵小白花放在上面。",effects:{"sanity":3,"yin":-3},choices:[createChoice({"text":"在坟前磕个头","next":"huimen_exp_moonlit_grave_bow","effects":{"sanity":5,"yin":-5}}),createChoice({"text":"继续往前走","next":"huimen_exp_moonlit_path_end","effects":{"yin":1}}),createChoice({"text":"在秀兰坟旁种一棵松树","next":"huimen_exp_little_pine_alt"})]}),
    huimen_exp_moonlit_grave_bow: createScene('huimen_exp_moonlit_grave_bow', {title:"无名祭",text:"你跪在坟前，磕了三个头。\n\n\"我不知道你是谁。\" 你说，\"但我知道你受过委屈。我替你磕个头，愿你来生，能做个幸福的人。\"\n\n坟头的石头忽然裂了一道缝，缝里飘出一缕青烟。青烟在空中凝成一个人形，朝你福了一福。\n\n\"谢谢。\" 她说，\"我叫阿绣。三十年了，第一次有人给我磕头。\"\n\n她的身影消散在月光里。你站起身，感到胸口的压抑又轻了一些。",effects:{"sanity":10,"yin":-8,"setFlag":"huimen_exp_honored_unknown_woman"},choices:[createChoice({"text":"继续往前走","next":"huimen_exp_moonlit_path_end","effects":{"yin":1}})]}),
    huimen_exp_moonlit_river: createScene('huimen_exp_moonlit_river', {title:"月下河",text:"月光小路尽头有一条河。\n\n河水是银色的，像流动的水银。河面上漂着许多纸船，每只船上都点着一根小蜡烛。\n\n你蹲在河边，看见河水里映出许多张脸。有秀兰、有柳红、有阿绣，还有很多你不认识的女子。\n\n\"渡河吧。\" 她们一起说，\"渡过去，你就自由了。\"\n\n可你知道，这条河不是给人渡的。它是给亡魂渡的。",effects:{"sanity":-8,"yin":3},choices:[createChoice({"text":"找船渡河","next":"huimen_exp_moonlit_river_cross","effects":{"yin":3}}),createChoice({"text":"沿河岸走","next":"huimen_exp_village_street","effects":{"yin":1}})]}),
    huimen_exp_moonlit_river_cross: createScene('huimen_exp_moonlit_river_cross', {title:"月夜渡河",text:"你找到一只小船，船夫是个穿蓑衣的老人。\n\n\"过河？\" 老人问。\n\n\"是。\" 你说。\n\n\"过河要付船钱。\" 他说，\"把你的名字写在船舷上。\"\n\n你拿起船上的笔，刚要写自己的名字，却停住了。\n\n[red]你把名字写在船上，岂不是把命交给了河？[/red]\n\n你转而写下\"周氏秀兰\"四个字。河水翻涌，船却平稳地驶向对岸。",effects:{"sanity":-5,"yin":2},choices:[createChoice({"text":"到对岸","next":"huimen_exp_moonlit_escape","effects":{"sanity":5,"yin":-5}})]})
};
