/**
 * 《回门》场景模块：exp_ancestral_hall
 */


import { createScene, createChoice } from '../../../js/engine/sceneFactory.js';

export const scenes = {
    huimen_exp_ancestral_hall: createScene('huimen_exp_ancestral_hall', {title:"周家祖祠",text:"你来到周家祖祠前。\n\n祖祠的门是朱红色的，门上的漆已经剥落，露出底下层层叠叠的黄符。每一张黄符上都写着一个名字，都是周家男丁。\n\n你推开门，里面是一排排牌位。牌位前的香炉里积着厚厚的香灰，香灰里插着几根没烧完的香。\n\n最上面的牌位写着\"周氏先祖\"，下面的牌位越来越小，最末一排，有一个空位。\n\n[red]那个空位旁边，已经刻好了你的名字。[/red]\n\n你伸手去摸那个名字，指尖触到木头的瞬间，所有牌位同时发出一声叹息。",effects:{"sanity":-10,"yin":3,"visual":"flicker","visualDuration":2000},choices:[createChoice({"text":"查看牌位后的暗格","next":"huimen_exp_ancestral_hall_vault","effects":{"yin":2}}),createChoice({"text":"跪拜祖先，请求宽恕","next":"huimen_exp_ancestor_judge_scene","effects":{"sanity":-5,"yin":3}}),createChoice({"text":"用香灰涂抹刻着自己名字的牌位","next":"huimen_exp_erase_name","condition":{"hasItem":"香灰"},"effects":{"sanity":5,"yin":-5}}),createChoice({"text":"查看角落里的画像","next":"huimen_exp_ancestral_painting","effects":{"yin":2}}),createChoice({"text":"去后墙看看那面女墙","next":"huimen_exp_ancestral_women_wall","condition":{"flag":"huimen_exp_read_ancestral_record"},"effects":{"yin":2}}),createChoice({"text":"寻找祖祠地下密室","next":"huimen_exp_ancestral_blood_pool","condition":{"flag":"huimen_exp_defied_ancestor"},"effects":{"yin":3}}),createChoice({"text":"离开祖祠","next":"huimen_exp_village_street","effects":{"yin":1}}),createChoice({"text":"把族谱上划掉的名字补回去","next":"huimen_exp3_zhou_mansion_cellar_name_stele","condition":{"flag":"huimen_exp3_knows_seven_women"},"effects":{"sanity":5,"yin":-2}}),createChoice({"text":"跪在祖宗牌位前，承认周家的罪","next":"huimen_exp_zhou_curse_alt"}),createChoice({"text":"寅时将近，是时候做最后抉择","next":"shichen_yin_entry","condition":{"timeAfter":1620},"hidden":true,"effects":{"time":30}}),createChoice({"text":"绕到祠堂后面查看","next":"investigate_ancestral_hall"})]}),
    huimen_exp_ancestral_hall_vault: createScene('huimen_exp_ancestral_hall_vault', {title:"暗格",text:"你挪开最老那座牌位，后面露出一方暗格。\n\n暗格里放着一本薄薄的册子，封面上写着\"周家秘录\"。你翻开第一页，上面记载着周家每一代\"不祥女\"的名字。\n\n秀兰、柳红、云袖、素心、月娥……每一个名字后面都写着\"活埋\"、\"配冥婚\"、\"沉塘\"。\n\n[red]周家不是靠男丁传宗接代，而是靠女人的血养着。[/red]\n\n你翻到最后一页，发现是空白的。空白页上只有一滴干涸的血，血旁边有一行小字：\n\n[faded]\"最后一个名字，由你写。\"[/faded]",effects:{"sanity":-15,"yin":3,"setFlag":"huimen_exp_read_ancestral_record"},choices:[createChoice({"text":"写下秀兰的名字，承认她的身份","next":"huimen_exp_restore_xiulan_name","effects":{"sanity":10,"yin":-10}}),createChoice({"text":"撕掉这本册子","next":"huimen_exp_burn_ancestral_record","effects":{"sanity":-10,"yin":5}}),createChoice({"text":"把册子带走","next":"huimen_exp_village_street","effects":{"yin":1,"addItem":"周家秘录"}})]}),
    huimen_exp_burn_ancestral_record: createScene('huimen_exp_burn_ancestral_record', {title:"焚册",text:"你点燃了周家秘录。\n\n火光照亮了祖祠，牌位上的名字在火中扭曲。你听见无数女子的哭声，从火光里传出来。\n\n\"你烧了我们的名字！\" 她们哭喊，\"我们连鬼都做不成了！\"\n\n你愣住了。你本想毁掉周家的罪证，却连她们最后的痕迹也烧掉了。\n\n火势蔓延到牌位上，整个祖祠开始燃烧。你想逃，却发现门已经被黄符封死。\n\n[red]你和周家的秘密，一起化成了灰。[/red]",effects:{"sanity":-20,"yin":10},ending:"huimen_exp_forgotten"})
};
