/**
 * 《回门》场景模块：main_extended_arrival
 */


import { createScene, createChoice } from '../../../js/engine/sceneFactory.js';

export const scenes = {
    huimen_village_gate: createScene('huimen_village_gate', {title:"入村",text:"你绕过老槐树，踏上进村的小路。\n\n村口立着一块石碑，碑身被青苔覆盖，字迹斑驳。你伸手拂去青苔，露出八个字：\n\n[faded]\"入村者三，出村者一。\"[/faded]\n\n你心头一凛。这是什么意思？是说三个人进来，只有一个人能出去？还是说……\n\n李婆的灯笼在你身后晃了晃：\"别看了。这碑立了三十年，每个字都是血写的。\"",effects:{"sanity":-3,"yin":2,"setFlag":"huimen_saw_village_stele"},choices:[createChoice({"text":"追问碑文含义","next":"huimen_read_stele","effects":{"yin":1}}),createChoice({"text":"快步走向老宅","next":"huimen_paper_doll_warning","effects":{"yin":1}}),createChoice({"text":"绕过石碑，从侧路进村","next":"huimen_paper_doll_warning","effects":{"sanity":-2,"yin":2}})]}),
    huimen_read_stele: createScene('huimen_read_stele', {title:"血碑",text:"你凑近石碑，借着灯笼光细看。\n\n碑的背面刻着密密麻麻的小字，都是名字。你一眼就认出了\"周\"字——那是周家的族谱，却被刻在这座入村的石碑上，像是一份诅咒的名单。\n\n\"这些名字，\"李婆说，\"都是三十年前那晚，亲眼看着秀兰被活埋的人。他们后来都死了，死法各不相同，但都有一个共同点——\"她顿了顿，\"死前都喊着一个名字。\"\n\n[whisper]\"秀兰。\"[/whisper]\n\n你摸了摸自己的手腕，那根红绳似乎又紧了一分。",effects:{"sanity":-5,"yin":3},choices:[createChoice({"text":"继续往老宅走","next":"huimen_paper_doll_warning","effects":{"yin":1}}),createChoice({"text":"在碑前站一会儿","next":"huimen_paper_doll_warning","effects":{"sanity":-3,"yin":2}})]}),
    huimen_paper_doll_warning: createScene('huimen_paper_doll_warning', {title:"纸人拦路",text:"你加快脚步，可那两个纸扎人不知何时挡在了路中央。\n\n它们的脸上还是那种诡异的笑，但男纸人的嘴微微张开，风里传来极细的声音：\n\n[whisper]\"别喝交杯酒……别喝……\"[/whisper]\n\n女纸人的头又转向你，这次你看见她的眼眶里不是墨点，而是两颗小小的、湿漉漉的眼泪。\n\n[red]它们不是在吓你。它们在警告你。[/red]\n\n李婆的灯笼突然灭了。黑暗中，纸人的声音更清晰了：\"子时之前，找到她的名字。找不到，你就是下一个新郎。\"",effects:{"sanity":-8,"yin":5,"setFlag":"heard_paper_whisper"},choices:[createChoice({"text":"问它们秀兰的名字在哪里","next":"huimen_old_house_gate","effects":{"sanity":-3,"yin":2}}),createChoice({"text":"绕过纸人，冲向老宅","next":"huimen_old_house_gate","effects":{"yin":1}}),createChoice({"text":"把纸人扶正，恭恭敬敬走过","next":"huimen_old_house_gate","effects":{"sanity":5,"yin":-2}})]}),
    huimen_after_li_po: createScene('huimen_after_li_po', {title:"李婆的背影",text:"你快步穿过村街，李婆的白灯笼在身后晃了晃，终究没有跟上来。\n\n可你越靠近老宅，空气越冷。路边的纸人一个个转过头，脸上画着的笑在月光下泛着惨白。你听见它们用极细的声音说：\"新郎官，慢点走，新娘子会跟不上的。\"\n\n你不敢回头。你知道，秀兰就在你身后某处，或许在井底，或许在纸人里，或许就在你脚下的影子里。\n\n老宅的轮廓出现在雾气中，门口那盏红灯笼亮得刺眼。",effects:{"sanity":-5,"yin":3},choices:[createChoice({"text":"继续走向老宅","next":"huimen_paper_doll_warning","effects":{"yin":1}}),createChoice({"text":"绕到后院看看","next":"huimen_exp_village_street","effects":{"yin":2}}),createChoice({"text":"站在原地，等秀兰现身","next":"huimen_paper_doll_warning","condition":{"flag":"knowsTruth"},"effects":{"sanity":-5,"yin":3}})]}),
    huimen_old_house_gate: createScene('huimen_old_house_gate', {title:"老宅门前",text:"你终于来到周家老宅门前。\n\n门没有关严，留着一条缝。缝里透出青白色的烛光，还有一股纸钱和檀香混合的味道。门板上贴着一张黄符，符上写着你的生辰八字。\n\n你伸手推门，门却自己\"吱呀\"一声开了。\n\n堂屋里跪着一群人，听见门响，齐刷刷地转过头来。他们的嘴角弯着同样的弧度，像被同一根线牵着的木偶。\n\n\"回来啦。\"他们说。",effects:{"sanity":-10,"yin":3},choices:[createChoice({"text":"迈进老宅","next":"to_old_house","effects":{"yin":1}}),createChoice({"text":"先在门外观察","next":"to_old_house","effects":{"sanity":-3,"yin":1}}),createChoice({"text":"转身离开","next":"huimen_exp_village_street","effects":{"sanity":-5,"yin":5}})]})
};
