/**
 * 《回门》场景模块：main_extended_truth
 */


import { createScene, createChoice } from '../../../js/engine/sceneFactory.js';

export const scenes = {
    huimen_red_coffin_discovery: createScene('huimen_red_coffin_discovery', {title:"井底红棺",text:"你跌跌撞撞冲到后院，井沿上的铜镜碎片在月光下泛着冷光。\n\n你不知哪来的勇气，抓着井绳滑了下去。井水冰凉刺骨，越往下越红。终于，你的脚踩到了硬物。\n\n那是一口红漆棺材，棺盖上钉着九根桃木钉，每根钉子上都缠着一张黄符。符上写着你的生辰八字。\n\n[red]这才是秀兰真正的棺木。[/red]\n\n棺材旁边散落着一些女子的饰物：一支银簪、半块玉佩、一束干枯的头发。你捡起银簪，簪头刻着两个字：\"照魂\"。",effects:{"sanity":-20,"yin":10,"addItem":"云袖银簪","setFlag":"found_red_coffin"},choices:[createChoice({"text":"用银簪撬开棺盖","next":"open_red_coffin","condition":{"hasItem":"云袖银簪"},"effects":{"sanity":-10,"yin":5}}),createChoice({"text":"去找铜钥匙","next":"find_bones","effects":{"yin":2}}),createChoice({"text":"先上去想想办法","next":"huimen_truth_revelation","effects":{"sanity":3,"yin":1}})]}),
    huimen_truth_revelation: createScene('huimen_truth_revelation', {title:"真相如刀",text:"你爬出井口，坐在井沿上喘气。\n\n月光照在无字碑上，碑身浮现出一行行血字：\n\n[faded]\"周家秀兰，年十六。与周家少爷有情，珠胎暗结。周家恐丑事外扬，于子时活埋于井底，对外宣称未婚卒。秀兰含冤三十年，求周家后人还我名分，令我归土。\"[/faded]\n\n你浑身发抖。\n\n[red]秀兰不是病死的。她是被周家活埋的。[/red]\n\n而那个周家少爷，正是你的祖父。你胸口那颗红痣突然发烫，像是某种烙印在回应这段血债。",effects:{"sanity":-15,"yin":5,"setFlag":"knowsTruth"},choices:[createChoice({"text":"回老宅找族谱","next":"huimen_seek_evidence","effects":{"yin":1}}),createChoice({"text":"去井底开棺，带她走","next":"huimen_red_coffin_discovery","effects":{"yin":2}}),createChoice({"text":"在碑前发誓为她正名","next":"swear_justice","effects":{"sanity":5,"yin":-5,"setFlag":"xiulanMercy"}})]}),
    huimen_seek_evidence: createScene('huimen_seek_evidence', {title:"寻证",text:"你悄悄摸进老宅东厢房。\n\n樟木箱底有一本泛黄的族谱。最后一页，秀兰的名字被墨水涂黑了，旁边用朱笔写着\"周氏不祥女\"五个字。\n\n你手指发抖，把涂黑的地方一点点刮开。\n\n秀兰。周家长子未婚妻。民国二十三年卒。\n\n[red]她不是不祥。她是被周家活埋的。[/red]\n\n你在她名字旁边，用颤抖的手写下：\"周氏秀兰，明媒正娶。\"刚写完最后一个字，窗外的纸钱忽然停了。远处传来一声似有似无的叹息。",effects:{"sanity":-10,"yin":-10,"setFlag":"restored_xiulan_name"},choices:[createChoice({"text":"把族谱带去给秀兰看","next":"huimen_family_tree_confront","effects":{"yin":1}}),createChoice({"text":"先去井底开棺","next":"huimen_red_coffin_discovery","effects":{"yin":2}}),createChoice({"text":"在祠堂公开族谱","next":"huimen_exp_zhou_women_alt","effects":{"sanity":5,"yin":-3}})]}),
    huimen_family_tree_confront: createScene('huimen_family_tree_confront', {title:"对簿",text:"你带着改写过的族谱回到井边。\n\n秀兰的身影从井水里浮出来。她看着你手里的族谱，眼眶里红色的泪光闪烁。\n\n\"你……真的把我的名字写回去了？\"她的声音很轻，像怕惊碎什么。\n\n\"不只是名字。\"你说，\"我把'不祥女'三个字也划掉了。你是周家的人，从来都是。\"\n\n秀兰伸出手，苍白的手指穿过族谱纸页。纸页上的墨迹忽然亮了一下，像是被什么力量认可了。\n\n\"三十年，\"她说，\"我等了三十年，就想听周家人说一句：你是我的。\"",effects:{"sanity":10,"yin":-15,"setFlag":"xiulanMercy"},choices:[createChoice({"text":"现在我可以带你走了","next":"huimen_prepare_burial","effects":{"yin":1}}),createChoice({"text":"先解开红棺的封印","next":"open_red_coffin","effects":{"yin":2}}),createChoice({"text":"让族谱上的所有女子都被看见","next":"huimen_exp_zhou_women_alt","effects":{"sanity":5,"yin":-5}})]})
};
